[project]
name = "portfolio-book"

[dependencies]
ggmice = "*"
gt = "*"
janitor = "*"
mice = "*"
naniar = "*"
pins = "*"
skimr = "*"
tidyverse = "*"
withr = "*"

[dependencies.uvr]
git = "nbafrank/uvr-r"
